### PR TITLE
Double chop in pure CUDA + CuPy demo

### PR DESCRIPTION
**Pull request by leofang**
It's 1:30am and I'm too tired to write a detailed PR description as I normally would. Pin me if you need any explanation!

### CODE REVIEW

**Comment by leofang** [comment]
On P100:
```shell
launching CUDA kernel from CuPy took 46.98460896809896 ms in average
launching Numba jit kernel took 105.38910166422527 ms in average
```

**Comment by leofang** [comment]
You should time it with the combination of Numba arrays + Numba jit kernel for a fairer comparison. Not sure if it is accessing `__cuda_array_interface__` that took some time. I hope not...

**Comment by beckermr** [comment]
ouch. numba being 2x slower is a real problem if it is true...

**Comment by beckermr** [comment]
I wonder if we are not getting actual floats in the numba kernel even if we pass in float arrays.

**Comment by leofang** [comment]
> I wonder if we are not getting actual floats in the numba kernel even if we pass in float arrays.

Not sure what you meant by this. But, be careful with the instantiation of the Numba kernels. In my demo, `cell1` and `indx2` were of type int32, but I suspect in your tests they were of type float32 (I didn't check the latter, just based on my impression, and I could be wrong).

**Comment by beckermr** [comment]
Right. What I mean is that if the numba kernels are executing in double precision, then they would be roughly 2x slower than the cuda kernel which we know is executing in float. The GPU has many fewer double precision units than float ones.

**Comment by beckermr** [comment]
I did some timing tests locally. Having the results array in double as opposed to float resulted in a 2x increase in the run time. So I think this may not be so much C versus numba but more about what types we are using.

**Comment by beckermr** [comment]
This also means we may need to switch to multiple kernel invocations so that we can accumulate partial results in float64 on the cpu

**Comment by leofang** [comment]
It seems @beckermr has merged this PR into master. Closing it.

**Pull request closed without merging**
